### ISSUE TITLE
FEATURE REQUEST: Project "job" board

### ISSUE THREAD

**Issue by chonger878** [OrcaSquad/orcasquad.win#15]
### What Is The Feature You Propose

I was envisioning a virtual "job" board (well, it could just be a project board), where people can post ideas about projects they would like to collaborate/work on.  

### Why This Feature Adds Value

I love taking on projects to help me improve my coding skills and I would love to take an opportunity to show that I can do the job.  Implementing this project "job" board might not only give users opportunities to show off their coding skills, but it could be a great opportunity for networking as well.

### How Would You Implement This Feature

Each "posting" could contain both information about the project and a link to the GitHub repository/wherever else the source code is located.  The idea I have in mind is that there is a button to sign up with an onClick event listener, so when the button is clicked, there is some sort of an alert that acknowledges that user is signed up for the project and that the project lead will be notified via email.  I am still considering if there should be a cap to how many people there should be per project.

**Comment by ImMattDavison** [comment]
> ### What Is The Feature You Propose
> I was envisioning a virtual "job" board (well, it could just be a project board), where people can post ideas about projects they would like to collaborate/work on.
> 
> ### Why This Feature Adds Value
> I love taking on projects to help me improve my coding skills and I would love to take an opportunity to show that I can do the job. Implementing this project "job" board might not only give users opportunities to show off their coding skills, but it could be a great opportunity for networking as well.
> 
> ### How Would You Implement This Feature
> Each "posting" could contain both information about the project and a link to the GitHub repository/wherever else the source code is located. The idea I have in mind is that there is a button to sign up with an onClick event listener, so when the button is clicked, there is some sort of an alert that acknowledges that user is signed up for the project and that the project lead will be notified via email. I am still considering if there should be a cap to how many people there should be per project.

For now I believe GitHub issues will suffice for this. If we were to produce this it would likely be an alternative project altogether!
