### ISSUE TITLE
Update Global Colours

### ISSUE THREAD

**Issue by louisefindlay23** [OrcaSquad/orcasquad.win#16]
### What Is The Feature You Propose

Update the colour scheme in the global CSS file and set brand colours accordingly. 

### Why This Feature Adds Value

To define the OrcaSquad branding.

### How Would You Implement This Feature

Update the global CSS file with primary: #00234B and secondary: #ffffff. Either CSS variables or colour classes.

**Comment by ImMattDavison** [comment]
Perfect - are you happy to PR this?
