### ISSUE TITLE
Feature Request: Add Logo to Header

### ISSUE THREAD

**Issue by louisefindlay23** [OrcaSquad/orcasquad.win#27]
### What Is The Feature You Propose

Add logo to the website header.

### Why This Feature Adds Value

Established OrcaSquad branding.

### How Would You Implement This Feature

Link the logo SVG in public/assets. Use Flexbox CSS for layout.

**Comment by ImMattDavison** [comment]
Hey @louisefindlay23 can I assign this to you?

**Comment by louisefindlay23** [comment]
> Hey @louisefindlay23 can I assign this to you?

Sure. Hopefully work on it tomorrow.
