### ISSUE TITLE
BUG REPORT: the OrcaSquad.win website link 

### ISSUE THREAD

**Issue by akshaya-hub** [OrcaSquad/orcasquad.win#45]
### Describe The Bug
the website link  of readme file is not working 

### Expected Behavior

What should happen instead?

### How Do We Reproduce This?

How can we reproduce this bug?

**Comment by ImMattDavison** [comment]
Hi @akshaya-hub the website is still under development and is not yet online

**Comment by akshaya-hub** [comment]
okay
