### ISSUE TITLE
Create Issue & PR Template

### ISSUE THREAD

**Issue by louisefindlay23** [OrcaSquad/orcasquad.win#8]
It would be good to add a PR & Issue Template to standarise how issues and PRs should be made to ensure they are documented well. This will help us when reviewing code.

[Example PR Template I've Used Previously](https://github.com/MLH-Fellowship/gitcord-bot/blob/main/pull_request_template.md)

**Comment by ImMattDavison** [comment]
Yes, these are definitely necessary, please feel free to PR them, alternatively I can add them!
